name: Build special assembly of distributive

on:
  push:
    branches-ignore:
      - master
      - version-*
      - dependabot**
    paths-ignore:
      - README.md
      - 'local-run/**'

jobs:
  license-check:
    uses: th2-net/.github/.github/workflows/license_check.yml@main
  owasp-scan:
    uses: th2-net/.github/.github/workflows/owasp-gradle-scan.yml@main
    with:
      multiproject: false
      javaVersion: 11
      javaVendor: 'zulu'
    secrets:
      nvd-api-key: ${{ secrets.NVD_APIKEY }}
  build-gradle:
    name: Build project
    runs-on: ubuntu-20.04
    needs: [ owasp-scan, license-check ]
    steps:
      - uses: actions/checkout@v4
      - name: Get branch name
        id: branch
        run: echo "branch_name=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Get SHA of the commit
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Get release_version
        id: ver
        uses: BrycensRanch/read-properties-action@v1.0.4
        with:
          file: gradle.properties
          property: release_version
      - name: Build custom release version
        id: release_ver
        run: echo "value="${{ steps.ver.outputs.release_version }}-${{ steps.branch.outputs.branch_name }}-${{ github.run_id }}-${{ steps.sha.outputs.sha_short }}"" >> $GITHUB_OUTPUT
      - name: Show custom release version
        run: echo ${{ steps.release_ver.outputs.value }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper
      - name: Build with Gradle
        run: ./gradlew --info -Prelease_version=${{ steps.release_ver.outputs.value }} clean build
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml
            build/test-results/**/*.trx
            build/test-results/**/*.json
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: th2-event-uploader-${{ steps.release_ver.outputs.value }}
          path: build/distributions/*.zip
          retention-days: 14